import { Link } from 'react-router-dom';

const OFFICIAL_SITE = 'https://iisauha.github.io/iisauhwallet/';

export function PrivacyPage() {
  return (
    <div className="tab-panel active" style={{ maxWidth: 720, margin: '0 auto', paddingBottom: 80 }}>
      <div className="card" style={{ padding: 20, marginBottom: 24 }}>
        <h1 style={{ margin: '0 0 8px 0', fontSize: '1.5rem', fontWeight: 700, color: 'var(--ui-title-text, var(--text))' }}>
          Security &amp; Privacy Policy — iisauh wallet
        </h1>
        <p style={{ margin: 0, fontSize: '0.9rem', color: 'var(--ui-primary-text, var(--muted))' }}>Last updated: March 2026</p>
      </div>

      <section className="card" style={{ padding: 20, marginBottom: 16 }}>
        <h2 style={{ margin: '0 0 12px 0', fontSize: '1.1rem', fontWeight: 700, color: 'var(--ui-title-text, var(--text))' }}>
          Local-first storage
        </h2>
        <p style={{ margin: 0, color: 'var(--ui-primary-text, var(--text))', lineHeight: 1.6 }}>
          All wallet data is stored locally in your browser on your device. The creator does not have access to your financial data. Data is not stored on a central server by default. Your information stays under your control.
        </p>
      </section>

      <section className="card" style={{ padding: 20, marginBottom: 16 }}>
        <h2 style={{ margin: '0 0 12px 0', fontSize: '1.1rem', fontWeight: 700, color: 'var(--ui-title-text, var(--text))' }}>
          Manual input — no automatic bank connection
        </h2>
        <p style={{ margin: 0, color: 'var(--ui-primary-text, var(--text))', lineHeight: 1.6 }}>
          This app does not connect directly to your bank by default. Users manually enter balances and transactions. Financial data is not automatically pulled from bank accounts. There is absolutely no direct connection to your bank by default. All financial information is manually entered unless you explicitly enable optional features.
        </p>
      </section>

      <section className="card" style={{ padding: 20, marginBottom: 16 }}>
        <h2 style={{ margin: '0 0 12px 0', fontSize: '1.1rem', fontWeight: 700, color: 'var(--ui-title-text, var(--text))' }}>
          Passcode and recovery system
        </h2>
        <p style={{ margin: 0, color: 'var(--ui-primary-text, var(--text))', lineHeight: 1.6 }}>
          The app offers passcode protection so only you can open it on your device. You can optionally set a password hint, a recovery key (generated by the app and shown once), and two security questions. These are stored only on your device. After too many failed passcode or recovery attempts, the app may offer a local wipe so you can start fresh; you can re-import a previous JSON backup to restore your data. The creator cannot access your passcode, recovery key, or security answers.
        </p>
      </section>

      <section className="card" style={{ padding: 20, marginBottom: 16 }}>
        <h2 style={{ margin: '0 0 12px 0', fontSize: '1.1rem', fontWeight: 700, color: 'var(--ui-title-text, var(--text))' }}>
          Creator access limitations
        </h2>
        <p style={{ margin: 0, color: 'var(--ui-primary-text, var(--text))', lineHeight: 1.6 }}>
          The creator cannot access your financial data. The creator cannot see your passcode or recovery key. The creator cannot access your locally stored data. The creator will NEVER ask you for your passcode, recovery key, or financial data. The creator will NEVER send you a different link to log in to this application. The official site is and will always be:
        </p>
        <p style={{ margin: '12px 0 0 0', color: 'var(--accent)', fontWeight: 600, wordBreak: 'break-all' }}>
          {OFFICIAL_SITE}
        </p>
      </section>

      <section className="card" style={{ padding: 20, marginBottom: 16 }}>
        <h2 style={{ margin: '0 0 12px 0', fontSize: '1.1rem', fontWeight: 700, color: 'var(--ui-title-text, var(--text))' }}>
          Security tips
        </h2>
        <ul style={{ margin: 0, paddingLeft: 20, color: 'var(--ui-primary-text, var(--text))', lineHeight: 1.7 }}>
          <li>Save your recovery key in a safe place when the app shows it.</li>
          <li>Export JSON backups regularly (Settings → Export JSON).</li>
          <li>Create a passcode you will remember.</li>
          <li>Do not share your recovery key with anyone.</li>
          <li>Only use the official site link above.</li>
          <li>Be careful with exported files; they may contain sensitive financial information.</li>
        </ul>
      </section>

      <section className="card" style={{ padding: 20, marginBottom: 16 }}>
        <h2 style={{ margin: '0 0 12px 0', fontSize: '1.1rem', fontWeight: 700, color: 'var(--ui-title-text, var(--text))' }}>
          Transparency
        </h2>
        <p style={{ margin: 0, color: 'var(--ui-primary-text, var(--text))', lineHeight: 1.6 }}>
          This application is a personal finance tracking tool. It does not provide financial advice and is not a financial institution.
        </p>
      </section>

      <section className="card" style={{ padding: 20, marginBottom: 24 }}>
        <h2 style={{ margin: '0 0 12px 0', fontSize: '1.1rem', fontWeight: 700, color: 'var(--ui-title-text, var(--text))' }}>
          Questions &amp; contact
        </h2>
        <p style={{ margin: 0, color: 'var(--ui-primary-text, var(--text))', lineHeight: 1.6 }}>
          If you have any questions about this Security &amp; Privacy Policy, you may contact:<br />
          <a href="mailto:iisauhaguilar@gmail.com" style={{ color: 'var(--accent)' }}>iisauhaguilar@gmail.com</a>
        </p>
      </section>

      <p style={{ textAlign: 'center', marginBottom: 24 }}>
        <Link to="/" className="btn btn-secondary" style={{ textDecoration: 'none' }}>
          Back to app
        </Link>
      </p>
    </div>
  );
}
